name: Python application deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest -v

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # Hostname or IP address of your server
          username: ${{ secrets.SERVER_USERNAME }}  # Username for SSH access
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key, you can use the contents of your PEM file here
          script: |
            cd /home/ubuntu/  # Change to the directory where your application resides
            git pull origin main  # Pull the latest changes from your repository
            # Assuming your application can be started with a command like 'python app.py'
            nohup python app.py &  # Start the application in the background
